const GalleryActionTypes = {
    SET_GALLERY:'SET_GALLERY',
//     SET_CURRENT_ARTWORK:'SET_CURRENT_ARTWORK',
    FETCH_GALLERY_START: 'FETCH_GALLERY_START',
    FETCH_GALLERY_SUCCESS:'FETCH_GALLERY_SUCCESS',
    FETCH_GALLERY_FAILURE: 'FETCH_GALLERY_FAILURE'
}

export default GalleryActionTypes